feat: Move to yauzl to fix FD error (#264)
`unzipper` would throw an FD error occasionally.
Relevant issue: https://github.com/ZJONSSON/node-unzipper/issues/104
There is a pending PR,
but it seemed simpler to simply move to `yauzl`.

The error:

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
Emitted 'error' event at:
    at lazyFs.read (internal/fs/streams.js:165:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:467:17)
```